spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://timescaledb:5432/cowinfo
    username: postgres
    password: password
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false

grpc:
  server-config:
    host: localhost
    port: 8080
  server:
    port: 9091
    host: localhost

cde:
  swagger:
    enabled: true
  ssl:
    enabled: false
  log:
    requests: true

logging:
  level:
    com.cde: INFO
    org.springframework.web: INFO